In [56]:
import glob
import os
import pandas as pd

path ='.../data' # use your path
allFiles = glob.glob("data/*.csv")

list_ = []
name=[]

for file_ in allFiles:
    name.append(os.path.basename(file_))
    df = pd.read_csv(file_, header=0,usecols=[0,4])
    list_.append(df)

frame = pd.concat(list_, axis = 1, ignore_index = True)


# frame.columns=[name]

In [44]:
f=pd.merge(list_[1],list_[2],on=['Date'])

In [58]:
frame.head(-3)

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,2016-02-19,2460.0,2016-02-19,800.0,2016-02-19,1278.160034,2016-02-19,1229.5,2016-02-19,892.000000,...,2016-02-19,505.500000,2016-02-19,374.700012,2016-02-19,61.799999,2016-02-19,46.750000,2016-02-19,374.000000
1,2016-02-22,2503.0,2016-02-22,794.0,2016-02-22,1294.800049,2016-02-22,1253.5,2016-02-22,899.000000,...,2016-02-22,510.000000,2016-02-22,378.200012,2016-02-22,63.119999,2016-02-22,47.380001,2016-02-22,371.799988
2,2016-02-23,2505.0,2016-02-23,796.0,2016-02-23,1278.160034,2016-02-23,1220.0,2016-02-23,878.000000,...,2016-02-23,508.500000,2016-02-23,377.200012,2016-02-23,62.930000,2016-02-23,46.660000,2016-02-23,376.899994
3,2016-02-24,2473.0,2016-02-24,810.0,2016-02-24,1272.959961,2016-02-24,1187.0,2016-02-24,856.500000,...,2016-02-24,503.500000,2016-02-24,373.500000,2016-02-24,62.200001,2016-02-24,46.840000,2016-02-24,377.600006
4,2016-02-25,2557.0,2016-02-25,900.0,2016-02-25,1292.719971,2016-02-25,1233.0,2016-02-25,874.500000,...,2016-02-25,512.500000,2016-02-25,384.299988,2016-02-25,70.639999,2016-02-25,47.869999,2016-02-25,391.500000
5,2016-02-26,2640.0,2016-02-26,890.0,2016-02-26,1298.959961,2016-02-26,1246.0,2016-02-26,870.000000,...,2016-02-26,512.000000,2016-02-26,388.799988,2016-02-26,72.129997,2016-02-26,46.220001,2016-02-26,377.100006
6,2016-02-29,2616.0,2016-02-29,885.0,2016-02-29,1316.640015,2016-02-29,1257.5,2016-02-29,858.000000,...,2016-02-29,513.000000,2016-02-29,388.600006,2016-02-29,72.400002,2016-02-29,47.799999,2016-02-29,393.399994
7,2016-03-01,2687.0,2016-03-01,887.0,2016-03-01,1327.040039,2016-03-01,1307.0,2016-03-01,855.500000,...,2016-03-01,511.000000,2016-03-01,409.600006,2016-03-01,73.070000,2016-03-01,48.580002,2016-03-01,406.899994
8,2016-03-02,2718.0,2016-03-02,889.5,2016-03-02,1310.400024,2016-03-02,1329.5,2016-03-02,847.500000,...,2016-03-02,504.500000,2016-03-02,407.799988,2016-03-02,73.269997,2016-03-02,47.919998,2016-03-02,399.700012
9,2016-03-03,2738.0,2016-03-03,878.0,2016-03-03,1290.640015,2016-03-03,1340.5,2016-03-03,856.000000,...,2016-03-03,499.700012,2016-03-03,399.000000,2016-03-03,72.580002,2016-03-03,47.320000,2016-03-03,393.200012
10,2016-03-04,2624.0,2016-03-04,869.0,2016-03-04,1284.400024,2016-03-04,1346.5,2016-03-04,859.000000,...,2016-03-04,507.000000,2016-03-04,398.700012,2016-03-04,73.239998,2016-03-04,47.509998,2016-03-04,391.799988
11,2016-03-07,2651.0,2016-03-07,886.0,2016-03-07,1268.800049,2016-03-07,1326.5,2016-03-07,888.000000,...,2016-03-07,500.500000,2016-03-07,395.399994,2016-03-07,72.750000,2016-03-07,47.500000,2016-03-07,391.399994
12,2016-03-08,2639.0,2016-03-08,908.5,2016-03-08,1265.680054,2016-03-08,1326.5,2016-03-08,880.000000,...,2016-03-08,496.700012,2016-03-08,392.000000,2016-03-08,70.629997,2016-03-08,48.040001,2016-03-08,383.000000
13,2016-03-09,2685.0,2016-03-09,936.0,2016-03-09,1262.560059,2016-03-09,1365.0,2016-03-09,865.000000,...,2016-03-09,501.000000,2016-03-09,394.899994,2016-03-09,69.769997,2016-03-09,48.049999,2016-03-09,388.000000
14,2016-03-10,2699.0,2016-03-10,918.0,2016-03-10,1242.800049,2016-03-10,1319.5,2016-03-10,853.500000,...,2016-03-10,494.100006,2016-03-10,358.600006,2016-03-10,68.949997,2016-03-10,47.590000,2016-03-10,378.100006
15,2016-03-11,2698.0,2016-03-11,909.0,2016-03-11,1264.640015,2016-03-11,1358.5,2016-03-11,894.000000,...,2016-03-11,496.500000,2016-03-11,366.500000,2016-03-11,70.150002,2016-03-11,49.000000,2016-03-11,385.000000
16,2016-03-14,2703.0,2016-03-14,967.5,2016-03-14,1263.599976,2016-03-14,1346.0,2016-03-14,903.500000,...,2016-03-14,497.500000,2016-03-14,366.600006,2016-03-14,70.309998,2016-03-14,48.810001,2016-03-14,392.500000
17,2016-03-15,2709.0,2016-03-15,951.5,2016-03-15,1270.880005,2016-03-15,1317.5,2016-03-15,900.000000,...,2016-03-15,497.200012,2016-03-15,365.799988,2016-03-15,69.209999,2016-03-15,48.880001,2016-03-15,396.600006
18,2016-03-16,2707.0,2016-03-16,987.5,2016-03-16,1270.880005,2016-03-16,1338.5,2016-03-16,934.500000,...,2016-03-16,502.000000,2016-03-16,372.399994,2016-03-16,68.790001,2016-03-16,49.080002,2016-03-16,400.000000
19,2016-03-17,2716.0,2016-03-17,1012.0,2016-03-17,1274.000000,2016-03-17,1355.0,2016-03-17,928.500000,...,2016-03-17,506.000000,2016-03-17,375.200012,2016-03-17,69.300003,2016-03-17,50.000000,2016-03-17,399.200012
20,2016-03-18,2750.0,2016-03-18,1045.0,2016-03-18,1269.839966,2016-03-18,1371.0,2016-03-18,940.000000,...,2016-03-18,497.100006,2016-03-18,375.500000,2016-03-18,69.900002,2016-03-18,50.290001,2016-03-18,400.799988
21,2016-03-21,2725.0,2016-03-21,1052.0,2016-03-21,1274.000000,2016-03-21,1370.5,2016-03-21,940.500000,...,2016-03-21,497.600006,2016-03-21,376.799988,2016-03-21,69.790001,2016-03-21,49.900002,2016-03-21,402.299988
22,2016-03-22,2726.0,2016-03-22,1055.0,2016-03-22,1268.800049,2016-03-22,1355.5,2016-03-22,940.000000,...,2016-03-22,498.799988,2016-03-22,380.200012,2016-03-22,69.360001,2016-03-22,48.299999,2016-03-22,408.500000
23,2016-03-23,2715.0,2016-03-23,1064.0,2016-03-23,1263.599976,2016-03-23,1346.0,2016-03-23,935.500000,...,2016-03-23,506.000000,2016-03-23,375.500000,2016-03-23,68.900002,2016-03-23,49.470001,2016-03-23,414.600006
24,2016-03-24,2659.0,2016-03-24,1038.0,2016-03-24,1260.479980,2016-03-24,1275.5,2016-03-24,910.000000,...,2016-03-24,498.500000,2016-03-24,369.899994,2016-03-24,68.050003,2016-03-24,47.000000,2016-03-24,415.100006
25,2016-03-29,2650.0,2016-03-29,1057.0,2016-03-29,1263.599976,2016-03-29,1294.0,2016-03-29,922.000000,...,2016-03-29,507.000000,2016-03-29,371.600006,2016-03-29,68.000000,2016-03-28,47.970001,2016-03-29,419.500000
26,2016-03-30,2710.0,2016-03-30,1033.0,2016-03-30,1279.199951,2016-03-30,1302.0,2016-03-30,926.000000,...,2016-03-30,512.000000,2016-03-30,373.000000,2016-03-30,67.800003,2016-03-29,48.910000,2016-03-30,425.000000
27,2016-03-31,2683.0,2016-03-31,1057.0,2016-03-31,1277.119995,2016-03-31,1301.0,2016-03-31,918.500000,...,2016-03-31,509.000000,2016-03-31,370.200012,2016-03-31,68.019997,2016-03-30,48.799999,2016-03-31,421.100006
28,2016-04-01,2624.0,2016-04-01,1064.0,2016-04-01,1287.520020,2016-04-01,1279.0,2016-04-01,908.000000,...,2016-04-01,501.500000,2016-04-01,364.100006,2016-04-01,67.949997,2016-03-31,49.040001,2016-04-01,415.500000
29,2016-04-04,2641.0,2016-04-04,1073.0,2016-04-04,1295.839966,2016-04-04,1290.5,2016-04-04,906.500000,...,2016-04-04,501.500000,2016-04-04,364.500000,2016-04-04,68.320000,2016-04-01,48.320000,2016-04-04,414.200012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2019-01-04,2592.0,2019-01-04,2620.0,2019-01-04,1637.000000,2019-01-04,1384.0,2019-01-04,971.000000,...,2019-01-04,473.000000,2019-01-04,321.899994,2019-01-04,52.799999,2019-01-08,28.389999,2019-01-04,449.000000
727,2019-01-07,2564.0,2019-01-07,2812.0,2019-01-07,1645.500000,2019-01-07,1394.5,2019-01-07,970.599976,...,2019-01-07,466.000000,2019-01-07,318.500000,2019-01-07,53.349998,2019-01-09,28.969999,2019-01-07,457.049988
728,2019-01-08,2612.0,2019-01-08,2878.0,2019-01-08,1657.000000,2019-01-08,1425.5,2019-01-08,985.000000,...,2019-01-08,474.799988,2019-01-08,323.100006,2019-01-08,53.700001,2019-01-10,28.790001,2019-01-08,470.049988
729,2019-01-09,2650.0,2019-01-09,2982.0,2019-01-09,1654.500000,2019-01-09,1429.5,2019-01-09,985.200012,...,2019-01-09,486.799988,2019-01-09,326.600006,2019-01-09,53.810001,2019-01-11,29.150000,2019-01-09,466.799988
730,2019-01-10,2646.0,2019-01-10,2930.0,2019-01-10,1675.500000,2019-01-10,1449.5,2019-01-10,986.400024,...,2019-01-10,491.399994,2019-01-10,323.799988,2019-01-10,54.779999,2019-01-14,28.950001,2019-01-10,463.500000
731,2019-01-11,2634.0,2019-01-11,2782.0,2019-01-11,1667.000000,2019-01-11,1447.0,2019-01-11,988.799988,...,2019-01-11,497.000000,2019-01-11,321.899994,2019-01-11,54.709999,2019-01-15,29.049999,2019-01-11,469.850006
732,2019-01-14,2598.0,2019-01-14,2760.0,2019-01-14,1653.500000,2019-01-14,1440.5,2019-01-14,975.000000,...,2019-01-14,496.600006,2019-01-14,321.100006,2019-01-14,55.540001,2019-01-16,27.910000,2019-01-14,465.149994
733,2019-01-15,2564.0,2019-01-15,2768.0,2019-01-15,1656.500000,2019-01-15,1449.0,2019-01-15,970.000000,...,2019-01-15,505.799988,2019-01-15,325.000000,2019-01-15,55.540001,2019-01-17,30.389999,2019-01-15,469.399994
734,2019-01-16,2571.0,2019-01-16,2792.0,2019-01-16,1631.000000,2019-01-16,1467.0,2019-01-16,970.000000,...,2019-01-16,505.399994,2019-01-16,324.799988,2019-01-16,56.130001,2019-01-18,30.530001,2019-01-16,469.950012
735,2019-01-17,2558.0,2019-01-17,2734.0,2019-01-17,1611.500000,2019-01-17,1449.0,2019-01-17,960.400024,...,2019-01-17,497.700012,2019-01-17,322.000000,2019-01-17,56.130001,2019-01-22,31.129999,2019-01-17,466.750000
736,2019-01-18,2642.0,2019-01-18,2758.0,2019-01-18,1619.000000,2019-01-18,1503.0,2019-01-18,983.200012,...,2019-01-18,510.000000,2019-01-18,326.200012,2019-01-18,58.000000,2019-01-23,31.270000,2019-01-18,474.899994
737,2019-01-21,2655.0,2019-01-21,2792.0,2019-01-21,1625.500000,2019-01-21,1503.0,2019-01-21,984.000000,...,2019-01-21,515.000000,2019-01-21,327.899994,2019-01-21,58.000000,2019-01-24,30.900000,2019-01-21,477.399994
738,2019-01-22,2608.0,2019-01-22,2810.0,2019-01-22,1627.500000,2019-01-22,1502.0,2019-01-22,968.000000,...,2019-01-22,511.600006,2019-01-22,330.500000,2019-01-22,57.430000,2019-01-25,31.750000,2019-01-22,471.850006
739,2019-01-23,2581.0,2019-01-23,2700.0,2019-01-23,1624.500000,2019-01-23,1487.5,2019-01-23,941.400024,...,2019-01-23,509.000000,2019-01-23,331.200012,2019-01-23,57.299999,2019-01-28,31.170000,2019-01-23,469.950012
740,2019-01-24,2615.0,2019-01-24,2668.0,2019-01-24,1613.000000,2019-01-24,1497.5,2019-01-24,962.000000,...,2019-01-24,513.000000,2019-01-24,334.600006,2019-01-24,57.680000,2019-01-29,31.250000,2019-01-24,471.000000
741,2019-01-25,2587.0,2019-01-25,2666.0,2019-01-25,1586.500000,2019-01-25,1505.0,2019-01-25,951.000000,...,2019-01-25,511.000000,2019-01-25,332.399994,2019-01-25,58.570000,2019-01-30,31.910000,2019-01-25,472.250000
742,2019-01-28,2595.0,2019-01-28,2560.0,2019-01-28,1583.000000,2019-01-28,1486.0,2019-01-28,938.599976,...,2019-01-28,504.399994,2019-01-28,332.700012,2019-01-28,57.000000,2019-01-31,31.590000,2019-01-28,471.450012
743,2019-01-29,2623.0,2019-01-29,2536.0,2019-01-29,1609.500000,2019-01-29,1481.0,2019-01-29,945.000000,...,2019-01-29,512.799988,2019-01-29,337.899994,2019-01-29,56.840000,2019-02-01,31.600000,2019-01-29,472.549988
744,2019-01-30,2647.0,2019-01-30,2550.0,2019-01-30,1641.500000,2019-01-30,1494.0,2019-01-30,952.000000,...,2019-01-30,514.000000,2019-01-30,339.000000,2019-01-30,58.330002,2019-02-04,31.850000,2019-01-30,471.950012
745,2019-01-31,2611.0,2019-01-31,2576.0,2019-01-31,1630.500000,2019-01-31,1485.5,2019-01-31,938.000000,...,2019-01-31,511.799988,2019-01-31,336.700012,2019-01-31,57.900002,2019-02-05,31.510000,2019-01-31,472.000000
746,2019-02-01,2650.0,2019-02-01,2580.0,2019-02-01,1632.000000,2019-02-01,1512.5,2019-02-01,947.599976,...,2019-02-01,516.400024,2019-02-01,343.600006,2019-02-01,58.180000,2019-02-06,31.290001,2019-02-01,476.000000
747,2019-02-04,2660.0,2019-02-04,2538.0,2019-02-04,1654.000000,2019-02-04,1514.0,2019-02-04,946.599976,...,2019-02-04,512.799988,2019-02-04,343.500000,2019-02-04,57.810001,2019-02-07,30.680000,2019-02-04,478.549988
748,2019-02-05,2712.0,2019-02-05,2630.0,2019-02-05,1692.000000,2019-02-05,1537.5,2019-02-05,955.200012,...,2019-02-05,521.799988,2019-02-05,345.899994,2019-02-05,58.040001,2019-02-08,29.950001,2019-02-05,480.149994
749,2019-02-06,2707.0,2019-02-06,2664.0,2019-02-06,1696.000000,2019-02-06,1548.0,2019-02-06,964.200012,...,2019-02-06,522.799988,2019-02-06,345.200012,2019-02-06,58.259998,2019-02-11,29.740000,2019-02-06,471.799988
750,2019-02-07,2649.0,2019-02-07,2602.0,2019-02-07,1758.000000,2019-02-07,1518.5,2019-02-07,942.599976,...,2019-02-07,518.400024,2019-02-07,343.299988,2019-02-07,57.200001,2019-02-12,29.969999,2019-02-07,465.899994
751,2019-02-08,2591.0,2019-02-08,2592.0,2019-02-08,1749.000000,2019-02-08,1478.0,2019-02-08,923.400024,...,2019-02-08,520.200012,2019-02-08,343.299988,2019-02-08,56.880001,2019-02-13,29.730000,2019-02-08,469.799988
752,2019-02-11,2658.0,2019-02-11,2650.0,2019-02-11,1746.000000,2019-02-11,1510.0,2019-02-11,944.599976,...,2019-02-11,520.599976,2019-02-11,340.700012,2019-02-11,57.720001,2019-02-14,29.160000,2019-02-11,471.750000
753,2019-02-12,2693.0,2019-02-12,2700.0,2019-02-12,1745.500000,2019-02-12,1520.0,2019-02-12,945.000000,...,2019-02-12,515.000000,2019-02-12,342.500000,2019-02-12,57.959999,2019-02-15,29.400000,2019-02-12,471.250000
754,2019-02-13,2704.0,2019-02-13,2732.0,2019-02-13,1758.500000,2019-02-13,1537.5,2019-02-13,952.000000,...,2019-02-13,517.400024,2019-02-13,349.500000,2019-02-13,57.860001,NaN,NaN,2019-02-13,475.200012
755,2019-02-14,2694.0,2019-02-14,2754.0,2019-02-14,1756.000000,2019-02-14,1517.0,2019-02-14,942.200012,...,2019-02-14,526.000000,2019-02-14,348.200012,2019-02-14,57.400002,NaN,NaN,2019-02-14,473.250000

In [64]:
df = frame.drop(frame.columns[[i for i in range(2,59,2)]], axis=1)  # df.columns is zero-based pd.Index

In [63]:
for i in range(1,10,2):
    print(i)

1
3
5
7
9

In [66]:
df.head(-3)

,0,1,3,5,7,9,11,13,15,17,...,41,43,45,47,49,51,53,55,57,59
0,2016-02-19,2460.0,800.0,1278.160034,1229.5,892.000000,46.660000,1553.0,3313.0,1162.0,...,6556.0,2.40758,10100.0,3038.0,1270.0,505.500000,374.700012,61.799999,46.750000,374.000000
1,2016-02-22,2503.0,794.0,1294.800049,1253.5,899.000000,46.360001,1545.0,3417.0,1184.0,...,6582.0,2.48168,10320.0,3082.0,1289.0,510.000000,378.200012,63.119999,47.380001,371.799988
2,2016-02-23,2505.0,796.0,1278.160034,1220.0,878.000000,46.080002,1522.0,3458.0,1164.0,...,6554.0,2.43470,10170.0,3072.0,1234.0,508.500000,377.200012,62.930000,46.660000,376.899994
3,2016-02-24,2473.0,810.0,1272.959961,1187.0,856.500000,46.630001,1514.0,3425.0,1150.0,...,6520.0,2.39800,10260.0,3050.0,1180.0,503.500000,373.500000,62.200001,46.840000,377.600006
4,2016-02-25,2557.0,900.0,1292.719971,1233.0,874.500000,46.759998,1495.0,3539.0,1168.0,...,6625.0,2.46766,10650.0,3056.0,1180.0,512.500000,384.299988,70.639999,47.869999,391.500000
5,2016-02-26,2640.0,890.0,1298.959961,1246.0,870.000000,46.700001,1494.0,3546.0,1172.0,...,6603.0,2.51657,10770.0,3108.0,1269.0,512.000000,388.799988,72.129997,46.220001,377.100006
6,2016-02-29,2616.0,885.0,1316.640015,1257.5,858.000000,46.950001,1506.0,3578.0,1183.0,...,6560.0,2.50030,10800.0,3145.0,1320.0,513.000000,388.600006,72.400002,47.799999,393.399994
7,2016-03-01,2687.0,887.0,1327.040039,1307.0,855.500000,48.860001,1543.0,3599.0,1204.0,...,6676.0,2.57471,10550.0,3227.0,1352.0,511.000000,409.600006,73.070000,48.580002,406.899994
8,2016-03-02,2718.0,889.5,1310.400024,1329.5,847.500000,49.419998,1510.0,3532.0,1194.0,...,6503.0,2.55648,10350.0,3240.0,1360.0,504.500000,407.799988,73.269997,47.919998,399.700012
9,2016-03-03,2738.0,878.0,1290.640015,1340.5,856.000000,49.380001,1485.0,3417.0,1190.0,...,6458.0,2.55298,9880.0,3322.0,1364.0,499.700012,399.000000,72.580002,47.320000,393.200012
10,2016-03-04,2624.0,869.0,1284.400024,1346.5,859.000000,49.950001,1552.0,3460.0,1203.0,...,6539.0,2.57271,9700.0,3452.0,1380.0,507.000000,398.700012,73.239998,47.509998,391.799988
11,2016-03-07,2651.0,886.0,1268.800049,1326.5,888.000000,49.970001,1533.0,3420.0,1202.0,...,6436.0,2.52000,9620.0,3456.0,1371.0,500.500000,395.399994,72.750000,47.500000,391.399994
12,2016-03-08,2639.0,908.5,1265.680054,1326.5,880.000000,48.680000,1536.0,3379.0,1193.0,...,6470.0,2.53446,9450.0,3455.0,1462.0,496.700012,392.000000,70.629997,48.040001,383.000000
13,2016-03-09,2685.0,936.0,1262.560059,1365.0,865.000000,49.349998,1533.0,3354.0,1201.0,...,6578.0,2.55101,9600.0,3448.0,1364.0,501.000000,394.899994,69.769997,48.049999,388.000000
14,2016-03-10,2699.0,918.0,1242.800049,1319.5,853.500000,49.320000,1494.0,3327.0,1184.0,...,6462.0,2.41000,9505.0,3400.0,1349.0,494.100006,358.600006,68.949997,47.590000,378.100006
15,2016-03-11,2698.0,909.0,1264.640015,1358.5,894.000000,50.349998,1521.0,3410.0,1206.0,...,6529.0,2.57014,9305.0,3446.0,1378.0,496.500000,366.500000,70.150002,49.000000,385.000000
16,2016-03-14,2703.0,967.5,1263.599976,1346.0,903.500000,50.080002,1544.0,3477.0,1215.0,...,6637.0,2.58677,9155.0,3463.0,1398.0,497.500000,366.600006,70.309998,48.810001,392.500000
17,2016-03-15,2709.0,951.5,1270.880005,1317.5,900.000000,49.939999,1507.0,3489.0,1211.0,...,6649.0,2.60218,9035.0,3439.0,1360.0,497.200012,365.799988,69.209999,48.880001,396.600006
18,2016-03-16,2707.0,987.5,1270.880005,1338.5,934.500000,51.080002,1516.0,3532.0,1208.0,...,6641.0,2.61121,9100.0,3466.0,1350.0,502.000000,372.399994,68.790001,49.080002,400.000000
19,2016-03-17,2716.0,1012.0,1274.000000,1355.0,928.500000,52.410000,1485.0,3464.0,1208.0,...,6671.0,2.55773,9005.0,3482.0,1336.0,506.000000,375.200012,69.300003,50.000000,399.200012
20,2016-03-18,2750.0,1045.0,1269.839966,1371.0,940.000000,53.240002,1514.0,3497.0,1206.0,...,6600.0,2.57291,8865.0,3500.0,1354.0,497.100006,375.500000,69.900002,50.290001,400.799988
21,2016-03-21,2725.0,1052.0,1274.000000,1370.5,940.500000,53.020000,1501.0,3512.0,1202.0,...,6646.0,2.60695,9025.0,3491.0,1344.0,497.600006,376.799988,69.790001,49.900002,402.299988
22,2016-03-22,2726.0,1055.0,1268.800049,1355.5,940.000000,52.900002,1504.0,3456.0,1205.0,...,6641.0,2.64651,9240.0,3546.0,1345.0,498.799988,380.200012,69.360001,48.299999,408.500000
23,2016-03-23,2715.0,1064.0,1263.599976,1346.0,935.500000,51.889999,1515.0,3522.0,1220.0,...,6706.0,2.64242,9245.0,3562.0,1367.0,506.000000,375.500000,68.900002,49.470001,414.600006
24,2016-03-24,2659.0,1038.0,1260.479980,1275.5,910.000000,51.450001,1501.0,3517.0,1213.0,...,6695.0,2.54500,9300.0,3530.0,1320.0,498.500000,369.899994,68.050003,47.000000,415.100006
25,2016-03-29,2650.0,1057.0,1263.599976,1294.0,922.000000,52.049999,1525.0,3550.0,1229.0,...,6714.0,2.62252,9360.0,3553.0,1319.0,507.000000,371.600006,68.000000,47.970001,419.500000
26,2016-03-30,2710.0,1033.0,1279.199951,1302.0,926.000000,53.049999,1520.0,3692.0,1246.0,...,6771.0,2.63228,9570.0,3651.0,1370.0,512.000000,373.000000,67.800003,48.910000,425.000000
27,2016-03-31,2683.0,1057.0,1277.119995,1301.0,918.500000,52.619999,1519.0,3752.0,1245.0,...,6730.0,2.63500,9705.0,3640.0,1365.0,509.000000,370.200012,68.019997,48.799999,421.100006
28,2016-04-01,2624.0,1064.0,1287.520020,1279.0,908.000000,52.020000,1528.0,3791.0,1251.0,...,6705.0,2.67109,9715.0,3562.0,1327.0,501.500000,364.100006,67.949997,49.040001,415.500000
29,2016-04-04,2641.0,1073.0,1295.839966,1290.5,906.500000,52.380001,1528.0,3782.0,1265.0,...,6734.0,2.65850,9760.0,3591.0,1310.0,501.500000,364.500000,68.320000,48.320000,414.200012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,2019-01-04,2592.0,2620.0,1637.000000,1384.0,971.000000,76.389999,1107.0,3808.0,1890.5,...,5964.0,4.54437,6595.0,6110.0,1698.0,473.000000,321.899994,52.799999,28.389999,449.000000
727,2019-01-07,2564.0,2812.0,1645.500000,1394.5,970.599976,76.010002,1100.0,3922.0,1879.5,...,5925.0,4.59669,6735.0,6200.0,1700.0,466.000000,318.500000,53.349998,28.969999,457.049988
728,2019-01-08,2612.0,2878.0,1657.000000,1425.5,985.000000,76.379997,1147.5,4010.0,1887.5,...,6030.0,4.67026,6810.0,6415.0,1736.5,474.799988,323.100006,53.700001,28.790001,470.049988
729,2019-01-09,2650.0,2982.0,1654.500000,1429.5,985.200012,76.250000,1149.5,4045.0,1901.0,...,6054.0,4.72182,6740.0,6530.0,1790.0,486.799988,326.600006,53.810001,29.150000,466.799988
730,2019-01-10,2646.0,2930.0,1675.500000,1449.5,986.400024,75.750000,1142.0,4034.0,1912.5,...,6097.0,4.77765,6590.0,6510.0,1742.0,491.399994,323.799988,54.779999,28.950001,463.500000
731,2019-01-11,2634.0,2782.0,1667.000000,1447.0,988.799988,75.820000,1165.0,4038.0,1912.5,...,6177.0,4.72295,6530.0,6405.0,1751.5,497.000000,321.899994,54.709999,29.049999,469.850006
732,2019-01-14,2598.0,2760.0,1653.500000,1440.5,975.000000,76.050003,1178.0,4035.0,1877.0,...,6145.0,4.61441,6260.0,6325.0,1758.0,496.600006,321.100006,55.540001,27.910000,465.149994
733,2019-01-15,2564.0,2768.0,1656.500000,1449.0,970.000000,76.790001,1170.0,4071.0,1877.5,...,6252.0,4.71394,6210.0,6325.0,1763.5,505.799988,325.000000,55.540001,30.389999,469.399994
734,2019-01-16,2571.0,2792.0,1631.000000,1467.0,970.000000,78.129997,1193.0,4057.0,1874.5,...,5990.0,4.73197,6235.0,6315.0,1758.0,505.399994,324.799988,56.130001,30.530001,469.950012
735,2019-01-17,2558.0,2734.0,1611.500000,1449.0,960.400024,77.080002,1169.0,4087.0,1908.0,...,5869.0,4.73310,6155.0,6295.0,1760.5,497.700012,322.000000,56.130001,31.129999,466.750000
736,2019-01-18,2642.0,2758.0,1619.000000,1503.0,983.200012,76.900002,1172.0,4168.0,1943.5,...,5978.0,4.74535,6240.0,6405.0,1787.5,510.000000,326.200012,58.000000,31.270000,474.899994
737,2019-01-21,2655.0,2792.0,1625.500000,1503.0,984.000000,77.879997,1161.5,4151.0,1957.5,...,6000.0,4.74814,6190.0,6485.0,1785.0,515.000000,327.899994,58.000000,30.900000,477.399994
738,2019-01-22,2608.0,2810.0,1627.500000,1502.0,968.000000,77.750000,1234.5,4157.0,1945.0,...,6029.0,4.61382,6205.0,6435.0,1776.0,511.600006,330.500000,57.430000,31.750000,471.850006
739,2019-01-23,2581.0,2700.0,1624.500000,1487.5,941.400024,77.250000,1280.0,4068.0,1950.0,...,5784.0,4.69000,6125.0,6320.0,1828.0,509.000000,331.200012,57.299999,31.170000,469.950012
740,2019-01-24,2615.0,2668.0,1613.000000,1497.5,962.000000,86.779999,1254.5,4100.0,1922.0,...,5593.0,4.59557,6120.0,6335.0,1822.5,513.000000,334.600006,57.680000,31.250000,471.000000
741,2019-01-25,2587.0,2666.0,1586.500000,1505.0,951.000000,86.660004,1292.5,4101.0,1905.0,...,5698.0,4.63448,6025.0,6240.0,1785.5,511.000000,332.399994,58.570000,31.910000,472.250000
742,2019-01-28,2595.0,2560.0,1583.000000,1486.0,938.599976,90.849998,1293.0,4162.0,1884.0,...,5703.0,4.58561,6085.0,6305.0,1758.0,504.399994,332.700012,57.000000,31.590000,471.450012
743,2019-01-29,2623.0,2536.0,1609.500000,1481.0,945.000000,89.099998,1277.5,4163.0,1930.0,...,5824.0,4.65700,6095.0,6375.0,1758.0,512.799988,337.899994,56.840000,31.600000,472.549988
744,2019-01-30,2647.0,2550.0,1641.500000,1494.0,952.000000,90.139999,1290.0,4263.0,1928.5,...,5865.0,4.71700,6240.0,6530.0,1811.5,514.000000,339.000000,58.330002,31.850000,471.950012
745,2019-01-31,2611.0,2576.0,1630.500000,1485.5,938.000000,90.019997,1264.0,4308.0,1912.0,...,5863.0,4.67641,6265.0,6405.0,1801.5,511.799988,336.700012,57.900002,31.510000,472.000000
746,2019-02-01,2650.0,2580.0,1632.000000,1512.5,947.599976,89.739998,1272.0,4324.0,1954.5,...,5874.0,4.70955,6380.0,6430.0,1831.5,516.400024,343.600006,58.180000,31.290001,476.000000
747,2019-02-04,2660.0,2538.0,1654.000000,1514.0,946.599976,89.389999,1272.5,4350.0,1969.5,...,5868.0,4.73809,6420.0,6510.0,1808.0,512.799988,343.500000,57.810001,30.680000,478.549988
748,2019-02-05,2712.0,2630.0,1692.000000,1537.5,955.200012,90.320000,1298.5,4430.0,2004.0,...,5960.0,4.84526,6515.0,6665.0,1878.0,521.799988,345.899994,58.040001,29.950001,480.149994
749,2019-02-06,2707.0,2664.0,1696.000000,1548.0,964.200012,90.900002,1320.0,4395.0,1984.5,...,5857.0,4.83901,6545.0,6700.0,1868.5,522.799988,345.200012,58.259998,29.740000,471.799988
750,2019-02-07,2649.0,2602.0,1758.000000,1518.5,942.599976,94.790001,1301.5,4322.0,1970.5,...,5861.0,4.74953,6380.0,6615.0,1845.5,518.400024,343.299988,57.200001,29.969999,465.899994
751,2019-02-08,2591.0,2592.0,1749.000000,1478.0,923.400024,94.160004,1281.5,4230.0,1978.0,...,5918.0,4.73900,6375.0,6510.0,1869.0,520.200012,343.299988,56.880001,29.730000,469.799988
752,2019-02-11,2658.0,2650.0,1746.000000,1510.0,944.599976,93.209999,1287.0,4327.0,2000.0,...,5961.0,4.78848,6365.0,6615.0,1908.5,520.599976,340.700012,57.720001,29.160000,471.750000
753,2019-02-12,2693.0,2700.0,1745.500000,1520.0,945.000000,95.099998,1265.5,4301.0,2009.0,...,6001.0,4.87195,6330.0,6585.0,1935.5,515.000000,342.500000,57.959999,29.400000,471.250000
754,2019-02-13,2704.0,2732.0,1758.500000,1537.5,952.000000,NaN,1282.0,4341.0,2022.0,...,6049.0,4.86881,6410.0,6610.0,1962.0,517.400024,349.500000,57.860001,NaN,475.200012
755,2019-02-14,2694.0,2754.0,1756.000000,1517.0,942.200012,NaN,1267.0,4339.0,2042.0,...,5998.0,4.88617,6260.0,6700.0,1956.0,526.000000,348.200012,57.400002,NaN,473.250000

In [67]:
df.to_csv("output.csv", index=False)

In [69]:
df=pd.read_csv('output.csv')

In [77]:
df.head(3)

,0,1,3,5,7,9,11,13,15,17,...,41,43,45,47,49,51,53,55,57,59
0,2016-02-19,2460.0,800.0,1278.160034,1229.5,892.0,46.660000,1553.0,3313.0,1162.0,...,6556.0,2.40758,10100.0,3038.0,1270.0,505.5,374.700012,61.799999,46.750000,374.000000
1,2016-02-22,2503.0,794.0,1294.800049,1253.5,899.0,46.360001,1545.0,3417.0,1184.0,...,6582.0,2.48168,10320.0,3082.0,1289.0,510.0,378.200012,63.119999,47.380001,371.799988
2,2016-02-23,2505.0,796.0,1278.160034,1220.0,878.0,46.080002,1522.0,3458.0,1164.0,...,6554.0,2.43470,10170.0,3072.0,1234.0,508.5,377.200012,62.930000,46.660000,376.899994

In [76]:
df['0'] = pd.to_datetime(df['0'])

In [78]:
df['0']

0     2016-02-19
1     2016-02-22
2     2016-02-23
3     2016-02-24
4     2016-02-25
5     2016-02-26
6     2016-02-29
7     2016-03-01
8     2016-03-02
9     2016-03-03
10    2016-03-04
11    2016-03-07
12    2016-03-08
13    2016-03-09
14    2016-03-10
15    2016-03-11
16    2016-03-14
17    2016-03-15
18    2016-03-16
19    2016-03-17
20    2016-03-18
21    2016-03-21
22    2016-03-22
23    2016-03-23
24    2016-03-24
25    2016-03-29
26    2016-03-30
27    2016-03-31
28    2016-04-01
29    2016-04-04
         ...
729   2019-01-09
730   2019-01-10
731   2019-01-11
732   2019-01-14
733   2019-01-15
734   2019-01-16
735   2019-01-17
736   2019-01-18
737   2019-01-21
738   2019-01-22
739   2019-01-23
740   2019-01-24
741   2019-01-25
742   2019-01-28
743   2019-01-29
744   2019-01-30
745   2019-01-31
746   2019-02-01
747   2019-02-04
748   2019-02-05
749   2019-02-06
750   2019-02-07
751   2019-02-08
752   2019-02-11
753   2019-02-12
754   2019-02-13
755   2019-02-14
756   2019-02-15
757   2019-02-18
758   2019-02-19
Name: 0, Length: 759, dtype: datetime64[ns]

In [47]:
f=pd.merge(list_[0],list_[1],on=['Date'])


for i in range(1,len(list_)-1):
    f=pd.merge(f,list_[i+1],on=['Date'])

In [55]:
f.head(100)

,Date,Close_x,Close_y,Close_x,Close_y,Close_x,Close_y,Close_x,Close_y,Close_x,...,Close_x,Close_y,Close_x,Close_y,Close_x,Close_y,Close_x,Close_y,Close_x,Close_y
0,2019-01-22,2608.0,2810.0,1627.5,1502.0,968.000000,77.080002,1234.5,4157.0,1945.0,...,6029.0,4.61382,6205.0,6435.0,1776.0,511.600006,330.500000,57.430000,31.129999,471.850006
1,2019-01-23,2581.0,2700.0,1624.5,1487.5,941.400024,76.900002,1280.0,4068.0,1950.0,...,5784.0,4.69000,6125.0,6320.0,1828.0,509.000000,331.200012,57.299999,31.270000,469.950012
2,2019-01-24,2615.0,2668.0,1613.0,1497.5,962.000000,77.879997,1254.5,4100.0,1922.0,...,5593.0,4.59557,6120.0,6335.0,1822.5,513.000000,334.600006,57.680000,30.900000,471.000000
3,2019-01-25,2587.0,2666.0,1586.5,1505.0,951.000000,77.750000,1292.5,4101.0,1905.0,...,5698.0,4.63448,6025.0,6240.0,1785.5,511.000000,332.399994,58.570000,31.750000,472.250000
4,2019-01-28,2595.0,2560.0,1583.0,1486.0,938.599976,77.250000,1293.0,4162.0,1884.0,...,5703.0,4.58561,6085.0,6305.0,1758.0,504.399994,332.700012,57.000000,31.170000,471.450012
5,2019-01-29,2623.0,2536.0,1609.5,1481.0,945.000000,86.779999,1277.5,4163.0,1930.0,...,5824.0,4.65700,6095.0,6375.0,1758.0,512.799988,337.899994,56.840000,31.250000,472.549988
6,2019-01-30,2647.0,2550.0,1641.5,1494.0,952.000000,86.660004,1290.0,4263.0,1928.5,...,5865.0,4.71700,6240.0,6530.0,1811.5,514.000000,339.000000,58.330002,31.910000,471.950012
7,2019-01-31,2611.0,2576.0,1630.5,1485.5,938.000000,90.849998,1264.0,4308.0,1912.0,...,5863.0,4.67641,6265.0,6405.0,1801.5,511.799988,336.700012,57.900002,31.590000,472.000000
8,2019-02-01,2650.0,2580.0,1632.0,1512.5,947.599976,89.099998,1272.0,4324.0,1954.5,...,5874.0,4.70955,6380.0,6430.0,1831.5,516.400024,343.600006,58.180000,31.600000,476.000000
9,2019-02-04,2660.0,2538.0,1654.0,1514.0,946.599976,90.139999,1272.5,4350.0,1969.5,...,5868.0,4.73809,6420.0,6510.0,1808.0,512.799988,343.500000,57.810001,31.850000,478.549988
10,2019-02-05,2712.0,2630.0,1692.0,1537.5,955.200012,90.019997,1298.5,4430.0,2004.0,...,5960.0,4.84526,6515.0,6665.0,1878.0,521.799988,345.899994,58.040001,31.510000,480.149994
11,2019-02-06,2707.0,2664.0,1696.0,1548.0,964.200012,89.739998,1320.0,4395.0,1984.5,...,5857.0,4.83901,6545.0,6700.0,1868.5,522.799988,345.200012,58.259998,31.290001,471.799988
12,2019-02-07,2649.0,2602.0,1758.0,1518.5,942.599976,89.389999,1301.5,4322.0,1970.5,...,5861.0,4.74953,6380.0,6615.0,1845.5,518.400024,343.299988,57.200001,30.680000,465.899994
13,2019-02-08,2591.0,2592.0,1749.0,1478.0,923.400024,90.320000,1281.5,4230.0,1978.0,...,5918.0,4.73900,6375.0,6510.0,1869.0,520.200012,343.299988,56.880001,29.950001,469.799988
14,2019-02-11,2658.0,2650.0,1746.0,1510.0,944.599976,90.900002,1287.0,4327.0,2000.0,...,5961.0,4.78848,6365.0,6615.0,1908.5,520.599976,340.700012,57.720001,29.740000,471.750000
15,2019-02-12,2693.0,2700.0,1745.5,1520.0,945.000000,94.790001,1265.5,4301.0,2009.0,...,6001.0,4.87195,6330.0,6585.0,1935.5,515.000000,342.500000,57.959999,29.969999,471.250000
16,2019-02-13,2704.0,2732.0,1758.5,1537.5,952.000000,94.160004,1282.0,4341.0,2022.0,...,6049.0,4.86881,6410.0,6610.0,1962.0,517.400024,349.500000,57.860001,29.730000,475.200012
17,2019-02-14,2694.0,2754.0,1756.0,1517.0,942.200012,93.209999,1267.0,4339.0,2042.0,...,5998.0,4.88617,6260.0,6700.0,1956.0,526.000000,348.200012,57.400002,29.160000,473.250000
18,2019-02-15,2698.0,2774.0,1743.5,1532.5,949.200012,95.099998,1278.5,4338.0,2027.0,...,6017.0,4.87764,6190.0,6680.0,1953.0,527.000000,350.200012,58.439999,29.400000,479.250000